# Generated by Django 6.0.5 on 2026-05-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reiger',
            new_name='Register',
        ),
    ]
