# Generated by Django 6.0.5 on 2026-05-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_reiger_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profileImage',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='roles',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
