# Generated by Django 6.0.5 on 2026-05-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_register_profileimage_register_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('serviceTypeId', models.CharField(max_length=100)),
                ('serviceMainCategories', models.CharField(max_length=100)),
                ('serviceDescriptions', models.CharField(max_length=100)),
                ('serviceAboutsUs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImagesOrVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('serviceTypeId', models.CharField(max_length=100)),
                ('serviceMainImages', models.CharField(max_length=100)),
                ('serviceMainVideos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('serviceType', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='contactNo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
