# Generated by Django 6.0.5 on 2026-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_register_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNowLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('mainLocations', models.CharField(max_length=100)),
            ],
        ),
    ]
