# Generated by Django 6.0.5 on 2026-05-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_booknowlocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNowAddons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('bookNowCakeTypeId', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookNowCakeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('bookNowOccasionsId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookNowOccasions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('BookNowOverviewsId', models.CharField(max_length=100)),
                ('occasionTitle', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('occasionPersonName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookNowOverviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('bookNowSelectionsTypeId', models.CharField(max_length=100)),
                ('booking_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('emailId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookNowScreenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('mainLocationsId', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('priceTitle', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('priceDescriptions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookNowSelectionsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('bookNowScreenTypeId', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time_slot', models.CharField(max_length=100)),
                ('no_of_people', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('priceDescriptions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookNowTermsandConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('bookNowAddonsId', models.CharField(max_length=100)),
                ('tc', models.CharField(max_length=100)),
                ('tcDescriptions', models.CharField(max_length=650)),
                ('tc1Title', models.CharField(max_length=100)),
                ('tc1Descriptions', models.CharField(max_length=800)),
                ('tc2Title', models.CharField(max_length=100)),
                ('tc2Descriptions', models.CharField(max_length=100)),
                ('tc3Title', models.CharField(max_length=100)),
                ('tc3Descriptions', models.CharField(max_length=800)),
            ],
        ),
    ]
