# Generated by Django 6.0.5 on 2026-05-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_booknowaddons_booknowcaketype_booknowoccasions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminId', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
                ('mainLocationsId', models.CharField(max_length=100)),
                ('bookNowScreenTypeId', models.CharField(max_length=100)),
                ('bookNowSelectionsTypeId', models.CharField(max_length=100)),
                ('BookNowOverviewsId', models.CharField(max_length=100)),
                ('bookNowOccasionsId', models.CharField(max_length=100)),
                ('bookNowCakeTypeId', models.CharField(max_length=100)),
            ],
        ),
    ]
