# Generated by Django 6.0.5 on 2026-06-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_userbookdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookdetails',
            name='bookNowSelectionsDate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookdetails',
            name='bookNowSelectionsTimeSlots',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookdetails',
            name='no_of_people',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookdetails',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookdetails',
            name='priceDescriptions',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
