# Generated by Django 6.0.5 on 2026-06-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_userbookdetails_booknowselectionsdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknowselectionstype',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookdetails',
            name='bookNowSelectionsStatus',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
