# Generated by Django 6.0.5 on 2026-06-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_booknowselectionstype_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNowSelectionsPeoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookNowSelectionsTypeId', models.CharField(max_length=100)),
                ('no_of_people', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('priceDescriptions', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='booknowselectionstype',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booknowselectionstype',
            name='no_of_people',
        ),
        migrations.RemoveField(
            model_name='booknowselectionstype',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booknowselectionstype',
            name='priceDescriptions',
        ),
    ]
