# Generated by Django 6.0.5 on 2026-06-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_booknowselectionspeoples_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknowselectionspeoples',
            name='bookNowSelectionsTypeId',
        ),
    ]
